### ISSUE TITLE
Support for creating new keychains and querying agains them

### ISSUE THREAD

**Issue by lox** [keybase/go-keychain#1]
We are operating off a fork of the old `go-osxkeychain` codebase for `aws-vault`: https://github.com/99designs/aws-vault/blob/master/keyring/keychain.go.

If you guys are interested, I'll open a PR for adding a `Keychain` type, along with a `NewKeychain` function for creating new keychains and an `AddItem` method on the `Keychain` type and a `SetMatchSearchList` on `Item` for searching specific keychains?

**Comment by akalin-keybase** [comment]
@gabriel?

**Comment by gabriel** [comment]
Sure
