### ISSUE TITLE
signal: killed

### ISSUE THREAD

**Issue by paddie** [keybase/go-keychain#10]
I'm unable to run `keychain.NewItem()` on OSX 10.12.5 (16F73) using `go1.8 darwin/amd64`. I keep getting a `signal: killed` with no other output in spite of me running print-lines before and after accessing anything keychain related. Might it be in the init it fails?

I am getting the same error when running `go test` in the repo as well, 

```golang
// main.go
func main() {
	fmt.Println("new")
	item := keychain.NewItem()
	fmt.Println("done")
	item.SetSecClass(keychain.SecClassGenericPassword)
	item.SetService("MyService")
	item.SetAccount("gabriel")
	item.SetLabel("A label")
	item.SetAccessGroup("A123456789.group.com.mycorp")
	item.SetData([]byte("toomanysecrets"))
	item.SetSynchronizable(keychain.SynchronizableNo)
	item.SetAccessible(keychain.AccessibleWhenUnlocked)

	fmt.Println("attempting to add..")
	err := keychain.AddItem(item)

	if err == keychain.ErrorDuplicateItem {
		fmt.Println("failed to add")
		fmt.Println(err)
		os.Exit(1)
	}
}
```

output:
```bash
> go run main.go
signal: killed
```

```bash
> go test
signal: killed
FAIL	github.com/keybase/go-keychain	0.004s
```

Does anyone have any ideas? Is there maybe a step I am missing?

**Comment by gabriel** [comment]
Are you on latest go? 1.8.3?
Do you have latest Xcode command line tools installed?

**Comment by paddie** [comment]
I have the latest Xcode command line tools installed (it uses software update to keep up and no news there). I re-installed version 1.8.3 before filing this bug, but my terminal does keep responding with `go version go1.8 darwin/amd64`..

**Comment by gabriel** [comment]
Can you startup Xcode and compile an empty project?

**Comment by paddie** [comment]
I do not have xcode installed, but it is my understanding that this command is enough to get the command line tools installed:

```bash
> xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

If that is not true, then it is absolutely my fault.

**Comment by garetht** [comment]
@paddie It seems that this was an issue that was fixed with Go 1.8.1 (https://github.com/golang/go/issues/19734), and if `go version` responds with `go1.8` it's referring to `1.8.0` rather than being vague about `1.8.3`.

**Comment by paddie** [comment]
Gotcha, thank you! I'll give it a go when I have a second!

Kind regards / Venlig hilsen

Patrick Madsen

**Comment by jmuldoon** [comment]
I was receiving the same issue with:
go version go1.8 darwin/amd64

I have updated to:
go version go1.9 darwin/amd64

which resolved the problem. Whatever it was this solved it. I likely was using a version of 1.8.[0-2], and could have resolved via your comments above, but thought this quick fix for those that can update directly to 9 will save some time.

**Comment by akalin-keybase** [comment]
Sounds like this is fixed.
