### ISSUE TITLE
MacOS 10.15 Deprecation

### ISSUE THREAD

**Issue by howardkitto** [keybase/go-keychain#54]
Updated MacOS earlier and now I'm getting this warning.

```
# github.com/keybase/go-keychain
cgo-gcc-prolog:203:11: warning: 'SecTrustedApplicationCreateFromPath' is deprecated: first deprecated in macOS 10.15 - No longer supported [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrustedApplication.h:59:10: note: 'SecTrustedApplicationCreateFromPath' has been explicitly marked deprecated here
```

**Comment by klauern** [comment]
Is there a better API that should be used instead?  I can only imagine that macOS <next version> will remove it, and then this issue pops up again?

**Comment by howardkitto** [comment]
It looks like this is the alternative method...
https://developer.apple.com/documentation/security/sectrustedapplicationref?language=objc

**Comment by kjmph** [comment]
More discussion here, as well:
https://forums.developer.apple.com/thread/118479

**Comment by joshblum** [comment]
closed via https://github.com/keybase/go-keychain/pull/60

**Comment by definoob** [comment]
This still happens.

**Comment by definoob** [comment]
![image](https://user-images.githubusercontent.com/54032883/117463948-2e8ffc80-af1e-11eb-9d1c-0f511abcf7b6.png)

![image](https://user-images.githubusercontent.com/54032883/117464086-52ebd900-af1e-11eb-9654-789adfbeabc6.png)

![image](https://user-images.githubusercontent.com/54032883/117464143-60a15e80-af1e-11eb-91df-54a2cd3a33ae.png)

**Comment by sonltcoder98** [comment]
Any update? Still struggle with the same problem.
