### ISSUE TITLE
Would CI via Github Actions be useful ?

### ISSUE THREAD

**Issue by doodlesbykumbi** [keybase/go-keychain#69]
I had created a pull request (https://github.com/keybase/go-keychain/pull/68) thinking there was no visibility into builds but then I saw the badge with Travis CI. Perhaps Githu Actions still has some use ? If so I'll recreate the PR. Just wanted to get confirmation before throwing away the work.

**Comment by joshblum** [comment]
Thanks for contributing but we are ok with travis.
