### ISSUE TITLE
Devices - New Paper Key

### ISSUE THREAD

**Issue by nhalstead** [keybase/go-keychain#9]
On the iOS app if you goto your Settings tab and Select "Devices" then select "+ Add New", then "Paper Key" it will generate a new Key. It seems that it requires you to click/slide the options saying that you wrote it down to continue/add it to your account.

You can just Click the Setting Page Button 2-3 times and it will go back and add the paper Key despite the user's confirmation selection (that it was copied down somewhere).
It added the paper Key when its generated not when the user confirms that they have a copy.

**Comment by gabriel** [comment]
Can you submit this feedback in https://github.com/keybase/client?
